def create_country_mapping():
    """
    Create comprehensive country name mapping dictionary.
    Keys are normalized (uppercase, no accents), values are standard English names.
    """
    mapping = {
        # Standard English names (self-mapping for already correct names)
        'UNITED STATES': 'United States',
        'UNITED KINGDOM': 'United Kingdom',
        'GERMANY': 'Germany',
        'FRANCE': 'France',
        'SPAIN': 'Spain',
        'ITALY': 'Italy',
        'NETHERLANDS': 'Netherlands',
        'BELGIUM': 'Belgium',
        'SWITZERLAND': 'Switzerland',
        'AUSTRIA': 'Austria',
        'POLAND': 'Poland',
        'PORTUGAL': 'Portugal',
        'GREECE': 'Greece',
        'SWEDEN': 'Sweden',
        'NORWAY': 'Norway',
        'DENMARK': 'Denmark',
        'FINLAND': 'Finland',
        'IRELAND': 'Ireland',
        'CZECHIA': 'Czechia',
        'HUNGARY': 'Hungary',
        'ROMANIA': 'Romania',
        'BULGARIA': 'Bulgaria',
        'CROATIA': 'Croatia',
        'SLOVAKIA': 'Slovakia',
        'SLOVENIA': 'Slovenia',
        'LITHUANIA': 'Lithuania',
        'LATVIA': 'Latvia',
        'ESTONIA': 'Estonia',
        'RUSSIA': 'Russia',
        'UKRAINE': 'Ukraine',
        'TURKEY': 'Turkey',
        'CHINA': 'China',
        'JAPAN': 'Japan',
        'SOUTH KOREA': 'South Korea',
        'INDIA': 'India',
        'INDONESIA': 'Indonesia',
        'THAILAND': 'Thailand',
        'VIETNAM': 'Vietnam',
        'PHILIPPINES': 'Philippines',
        'MALAYSIA': 'Malaysia',
        'SINGAPORE': 'Singapore',
        'PAKISTAN': 'Pakistan',
        'BANGLADESH': 'Bangladesh',
        'AUSTRALIA': 'Australia',
        'NEW ZEALAND': 'New Zealand',
        'BRAZIL': 'Brazil',
        'MEXICO': 'Mexico',
        'ARGENTINA': 'Argentina',
        'CHILE': 'Chile',
        'COLOMBIA': 'Colombia',
        'PERU': 'Peru',
        'VENEZUELA': 'Venezuela',
        'CANADA': 'Canada',
        'SOUTH AFRICA': 'South Africa',
        'EGYPT': 'Egypt',
        'NIGERIA': 'Nigeria',
        'KENYA': 'Kenya',
        'MOROCCO': 'Morocco',
        'ALGERIA': 'Algeria',
        'TUNISIA': 'Tunisia',
        'SAUDI ARABIA': 'Saudi Arabia',
        'ISRAEL': 'Israel',
        'UNITED ARAB EMIRATES': 'United Arab Emirates',
        'KUWAIT': 'Kuwait',
        'QATAR': 'Qatar',
        'OMAN': 'Oman',
        'BAHRAIN': 'Bahrain',
        'JORDAN': 'Jordan',
        'LEBANON': 'Lebanon',
        'IRAN': 'Iran',
        'IRAQ': 'Iraq',
        'AFGHANISTAN': 'Afghanistan',
        'NEPAL': 'Nepal',
        'SRI LANKA': 'Sri Lanka',
        'MYANMAR': 'Myanmar',
        'CAMBODIA': 'Cambodia',
        'LAOS': 'Laos',
        'MONGOLIA': 'Mongolia',
        'NORTH KOREA': 'North Korea',
        'TAIWAN': 'Taiwan',
        'HONG KONG': 'Hong Kong',
        'MACAU': 'Macau',
        'COSTA RICA': 'Costa Rica',
        'PANAMA': 'Panama',
        'CUBA': 'Cuba',
        'JAMAICA': 'Jamaica',
        'DOMINICAN REPUBLIC': 'Dominican Republic',
        'PUERTO RICO': 'Puerto Rico',
        'TRINIDAD AND TOBAGO': 'Trinidad and Tobago',
        'ECUADOR': 'Ecuador',
        'BOLIVIA': 'Bolivia',
        'PARAGUAY': 'Paraguay',
        'URUGUAY': 'Uruguay',
        'GUYANA': 'Guyana',
        'SURINAME': 'Suriname',
        'HONDURAS': 'Honduras',
        'NICARAGUA': 'Nicaragua',
        'EL SALVADOR': 'El Salvador',
        'GUATEMALA': 'Guatemala',
        'BELIZE': 'Belize',
        

        # Encoding Errors (Windows-1252 artifacts)
        'ESPAA': 'Spain',
        'ESPANA': 'Spain',
        'OSTERREICH': 'Austria',
        'BELGIE': 'Belgium',
        'COTE D\'IVOIRE': 'Côte d\'Ivoire',
        'COTE DIVOIRE': 'Côte d\'Ivoire',
        
        # Native Names - European
        'BELGIE': 'Belgium',
        'BELGIQUE': 'Belgium',
        'BRASIL': 'Brazil',
        'DEUTSCHLAND': 'Germany',
        'ALLEMAGNE': 'Germany',
        'ESPANA': 'Spain',
        'MEXICO': 'Mexico',
        'NEDERLAND': 'Netherlands',
        'PAYS-BAS': 'Netherlands',
        'PAISES BAJOS': 'Netherlands',
        'OSTERREICH': 'Austria',
        'AUTRICHE': 'Austria',
        'POLSKA': 'Poland',
        'POLOGNE': 'Poland',
        'SCHWEIZ': 'Switzerland',
        'SUISSE': 'Switzerland',
        'SVIZZERA': 'Switzerland',
        'SUIZA': 'Switzerland',
        'ITALIA': 'Italy',
        'ITALIE': 'Italy',
        'GRECE': 'Greece',
        'GRECIA': 'Greece',
        'ELLADA': 'Greece',
        
        # Native Names - Asia
        'CHINE': 'China',
        'ZHONGGUO': 'China',
        'NIPPON': 'Japan',
        'JAPON': 'Japan',
        'HANGUK': 'South Korea',
        'COREE DU SUD': 'South Korea',
        'COREA DEL SUR': 'South Korea',
        'BHARAT': 'India',
        'INDE': 'India',
        
        # Native Names - Americas
        'ESTADOS UNIDOS': 'United States',
        'ETATS-UNIS': 'United States',
        'STATI UNITI': 'United States',
        'CANADA': 'Canada',
        
        # Native Names - Eastern Europe
        'CESKA REPUBLIKA': 'Czechia',
        'REPUBLIQUE TCHEQUE': 'Czechia',
        'REPUBLIKA CZECH': 'Czechia',
        'CESKO': 'Czechia',
        'ROSSIYA': 'Russia',
        'RUSSIE': 'Russia',
        'RUSSKAIA FEDERATSIIA': 'Russia',
        'ROSJA': 'Russia',
        'UKRAINA': 'Ukraine',
        'MAGYARORSZAG': 'Hungary',
        'HONGRIE': 'Hungary',
        'ROMANIA': 'Romania',
        'ROUMANIE': 'Romania',
        
        # Common Abbreviations
        'UK': 'United Kingdom',
        'U.K.': 'United Kingdom',
        'GB': 'United Kingdom',
        'US': 'United States',
        'U.S.': 'United States',
        'USA': 'United States',
        'U.S.A.': 'United States',
        'UAE': 'United Arab Emirates',
        'U.A.E.': 'United Arab Emirates',
        'NL': 'Netherlands',
        'CH': 'Switzerland',
        'CZ': 'Czechia',
        'PL': 'Poland',
        'PT': 'Portugal',
        'ES': 'Spain',
        'IT': 'Italy',
        'FR': 'France',
        'DE': 'Germany',
        'AT': 'Austria',
        'BE': 'Belgium',
        'SE': 'Sweden',
        'NO': 'Norway',
        'DK': 'Denmark',
        'FI': 'Finland',
        'IE': 'Ireland',
        'GR': 'Greece',
        'TR': 'Turkey',
        'RU': 'Russia',
        'CN': 'China',
        'JP': 'Japan',
        'KR': 'South Korea',
        'IN': 'India',
        'BR': 'Brazil',
        'MX': 'Mexico',
        'CA': 'Canada',
        'AU': 'Australia',
        'NZ': 'New Zealand',
        'ZA': 'South Africa',
        'AR': 'Argentina',
        'CL': 'Chile',
        'CO': 'Colombia',
        'PE': 'Peru',
        'VE': 'Venezuela',
        'MY': 'Malaysia',
        'SG': 'Singapore',
        'TH': 'Thailand',
        'ID': 'Indonesia',
        'PH': 'Philippines',
        'VN': 'Vietnam',
        'PK': 'Pakistan',
        'BD': 'Bangladesh',
        'EG': 'Egypt',
        'NG': 'Nigeria',
        'KE': 'Kenya',
        'SA': 'Saudi Arabia',
        'IL': 'Israel',
        
        # Alternative English Names
        'UNITED STATES OF AMERICA': 'United States',
        'GREAT BRITAIN': 'United Kingdom',
        'ENGLAND': 'United Kingdom',
        'SCOTLAND': 'United Kingdom',
        'WALES': 'United Kingdom',
        'NORTHERN IRELAND': 'United Kingdom',
        'HOLLAND': 'Netherlands',
        'CZECH REPUBLIC': 'Czechia',
        'SOUTH KOREA': 'South Korea',
        'REPUBLIC OF KOREA': 'South Korea',
        'NORTH KOREA': 'North Korea',
        'DEMOCRATIC PEOPLE\'S REPUBLIC OF KOREA': 'North Korea',
        'PEOPLE\'S REPUBLIC OF CHINA': 'China',
        'RUSSIAN FEDERATION': 'Russia',
        'REPUBLIC OF IRELAND': 'Ireland',
        'HELLENIC REPUBLIC': 'Greece',
        'REPUBLIC OF TURKEY': 'Turkey',
        'TURKIYE': 'Turkey',
        
        # Special Cases with Parentheses
        'VENEZUELA (BOLIVARIAN REPUBLIC OF)': 'Venezuela',
        'BOLIVIA (PLURINATIONAL STATE OF)': 'Bolivia',
        'IRAN (ISLAMIC REPUBLIC OF)': 'Iran',
        'KOREA (REPUBLIC OF)': 'South Korea',
        'KOREA (DEMOCRATIC PEOPLE\'S REPUBLIC OF)': 'North Korea',
        'TANZANIA (UNITED REPUBLIC OF)': 'Tanzania',
        'MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)': 'North Macedonia',
        'MOLDOVA (REPUBLIC OF)': 'Moldova',
        'SYRIA (SYRIAN ARAB REPUBLIC)': 'Syria',
        'PALESTINE (STATE OF)': 'Palestine',
        'CONGO (DEMOCRATIC REPUBLIC OF THE)': 'Democratic Republic of the Congo',
        'CONGO (REPUBLIC OF THE)': 'Republic of the Congo',
        
        # Remove "THE" prefix
        'THE NETHERLANDS': 'Netherlands',
        'THE UNITED STATES': 'United States',
        'THE UNITED KINGDOM': 'United Kingdom',
        'THE BAHAMAS': 'Bahamas',
        'THE GAMBIA': 'Gambia',
    }
    
    return mapping